server:
  port: 5050
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:enjoy@a.com:7001/eureka,http://admin:enjoy@b.com:7002/eureka,http://admin:enjoy@c.com:7003/eureka