server:
  port: 6060
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@a.com:7001/eureka,http://admin:enjoy@b.com:7002/eureka,http://admin:enjoy@c.com:7003/eureka
  instance:
    instance-id: sc-eureka-provider-product-instanceName
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
spring:
  application:
    name: sc-eureka-provider-product-appNme